name: Run the Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: "Create Packages"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Arch PKGBUILD
        run: |
          mkdir -pv /tmp/RELEASE
          cp -v pkg/arch/PKGBUILD /tmp/RELEASE/
      - name:  Install DEB deps
        run: |
          sudo apt update
          sudo apt install devscripts debhelper-compat build-essential
      - name: Run DEB pkg script
        run: |
          pwd
          ls
          ls pkg
          ls pkg/debian
          bash pkg/debian/build-debian.sh
          mkdir -pv /tmp/RELEASE
          mv -v /tmp/maps-build-temp/maps*.deb /tmp/RELEASE/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/RELEASE/*
